---
Blog:
  template: jolla
  id: Blog-block
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/allison-thirion/
    - icon: envelope
      text: Email
      href: "mailto:mail.ajthirion4@gmail.com"  
---

::: {#Blog-block}
:::

# On Being a Modern Scientist and Being a Dietitian with a Blog

In my statistics course this semester, we were instructed to read Jeff Leek’s book, How to be a Modern Scientist. The book is full of helpful tips for having a successful academic career and even ten years on from publishing remains relevant to my area of science.

One piece of academic advice that Dr. Leek give is to consider blogging. He’s clearly not the only person with this advice, as I am writing this blog post for an assignment to help start my academic professional footprint. But when I first read this advice, I was confused. Dietitians, including ones with PhDs, blog, but not in a way that is taken seriously by academia.

Having a “nutrition blog” has a very non-academic connotation, not something that I think aligns with what Dr. Leek was going for. A quick Google search for dietitian blogs yields thousands of RDs touting healthy recipes, tips for weight loss, and advertisements for private practice counseling sessions. I could not think of any colleague or mentor I’ve had in an academic space that has an academic-focused blog, but I can count a few who have tried to build a following through posting about diet plans while holding up a bowl of vibrant salad in a well-lit kitchen. Even when adding “PhD” or other academic-focused terms to a search, the blogs that come up feel like they are softening their intent to be more digestible for public consumption. One blogger I found, who posted an excellent review of an article on phosphorus binders, described their blog as “stories about what eating and meal planning means to me.”

Social media has also exploded with dietitians, in many ways replacing the traditional blog. Creators like Dr. Jessica Knurick, PhD, RD ([\@drjessicaknurick](https://www.instagram.com/drjessicaknurick/)) and Dr. Rachel Paul, PhD, RD ([\@collegenutritionist](https://www.instagram.com/collegenutritionist/)) are some of the most-followed dietitians on Instagram and regularly include citations for articles, but similar to other dietitian-scientists, focus their work on public-focused content.

I think there are a multitude of reasons why blogging is more public-focused and less academic-focused in nutrition. There’s public demand for this type of content, financial incentives, the rampant battle against nutrition misinformation, the gender divide in nutrition and the connotations of being in a female-majority profession and having a blog. For many other areas of STEM, these aren’t factors.

As someone who hopes to be a clinician scientist someday, I like how my field leans into being clinicians and values using blogs as a communication tool to the general public. I wonder if there will come a day when academia can find more value in this type of work to the extent it could raise someone’s academic public profile in the way Dr. Leek hopes these platforms do.

```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="btn btn-primary" href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/" role="button" target="_blank" style="padding: 15px 30px;">View the tutorial for this template (+ download link)</a>
</div>
```
